development:
  clients:
    default:
      database: currency_converter_development
      hosts:
        - localhost:27017
      options:
        server_selection_timeout: 1
test:
  clients:
    default:
      database: currency_converter_test
      hosts:
        - localhost:27017

production:
  clients:
    default:
      uri: <%= ENV['MONGODB_URI'] %>
      options:
        skip_version_check: true
        safe: true